config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  get 'stats/' => 'stats#index', as: :stats

  get 'charts/' => 'charts#index', as: :charts

  get 'exchange/' => 'exchange#index', as: :exchange

  get 'bubble/' => 'welcome#bubble', as: :bubble
  
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ActiveRecord::Base

  include ActiveModel::SecurePassword
  has_secure_password

  before_save { |user| user.email = user.email.downcase }

  validates :username, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  # before_filter :authorize
  #reason there are two @@ is because it is a class variable
  @@testVar = 50

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  helper_method :current_user

  # def authorize
  #   redirect_to login_url, alert: "Not authorized" if current_user.nil?
  # end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  def index

    require 'httparty'

    @response = HTTParty.get("http://api.bitcoincharts.com/v1/markets.json")
    @parsed_response = JSON.parse(@response.body)
    #raise @parsed_response.inspect
  end

end

app/controllers/exchange_controller.rb
class ExchangeController < ApplicationController

  def index


  

     @response = HTTParty.get("https://www.okcoin.com/api/v1/trades.do")
     #@response = HTTParty.get("https://cex.io/api/trade_history/GHS/BTC")
     @parsed_response = JSON.parse(@response.body)
     #@limited_response = @parsed_response
     #binding.pry
     #@parsed_response.inspect
    @response_chart = HTTParty.get("https://blockchain.info/stats?format=json")
    @parsed_response_chart = JSON.parse(@response_chart.body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.where(email: params[:email]).first
        # first make sure we actually find a user
        # then see if user authenticates
        if user && user.authenticate(params[:password])
            # sets the cookie to the browser
            session[:user_id] = user.id
            redirect_to root_url
        else
            flash.now.alert = "Email or password is invalid"
            render "new"
            # redirect_to new_session_path
        end
    end

    def destroy
        # Kill our cookies!
        reset_session
        redirect_to root_path
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  require 'httparty'
  def index

    @IOlabel = ""
    @response = HTTParty.get("https://blockchain.info/stats?format=json")
    @parsed_response = JSON.parse(@response.body)
    ## searcharg is the parameter being passed
    searcharg = params[:addressSearch]
    ## Display message when searcharge is either nil or empty
    if searcharg == nil || searcharg == ""
      @customError = "Enter a valid bitcoin address"
      @show_data = false
    else
      @show_data = true
      myURL = "https://blockchain.info/address/" + searcharg 
      myURL = myURL + "?format=json"
      response = HTTParty.get(myURL)
      @rbody = JSON.parse(response.body)
      #@inputs = @rbody["txs"][0]["inputs"]


      @trans = @rbody["txs"]

      @outs = @rbody["txs"][0]["out"]
     
   
      @address = @rbody["address"]

    end
  rescue
    @customError = "Bitcoin address not found exist"
    @show_data = false
  ensure
        
    #Using @@ because testVar is a class variable
    @formVar = @@testVar + 10
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
    else
        render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    require 'httparty'
    @response = HTTParty.get("https://blockchain.info/stats?format=json")
    @parsed_response = JSON.parse(@response.body)
  end

  def bubble

    require 'httparty'
    @response = HTTParty.get("https://blockchain.info/stats?format=json")
    @parsed_response = JSON.parse(@response.body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charts/index.html.erb
<!-- Filter for just btcnCNY, okcoinCNY, bitfinexUSD, bitstampUSD, btceUSD -->

<table>
  <tr>
    <td>Market</td>
    <td>Price</td>
    <td>Average</td>
    <td>High</td>
    <td>Low</td>
    <td>Currency Volume</td>
  </tr>
<% @parsed_response.each do |r| %>
<tr>
  <td>
    <%= "#{r["symbol"]}" %>
  </td>
  <td>
    <%= "#{r["ask"]}" %>
  </td>
  <td>
    <%= "#{r["avg"]}" %>
  </td>
  <td>
    <%= "#{r["high"]}" %>
  </td>
  <td>
    <%= "#{r["low"]}" %>
  </td>
  <td>
    <%= "#{r["currency_volume"]}" %>
  </td>
</tr>
<% end %>

</table>
@parsed_response

app/views/exchange/index.html.erb
<div class="row">
    <div class="col-md-9" style="background-color: white;">

<link href="assets/src/nv.d3.css" rel="stylesheet" type="text/css">

<style>

body {
  overflow-y:scroll;
}

text {
  font: 12px sans-serif;
}

#chart1 svg {
  height: 500px;
  margin: 10px;
  min-width: 100px;
  min-height: 100px;
/*
  Minimum height and width is a good idea to prevent negative SVG dimensions...
  For example width should be =< margin.left + margin.right + 1,
  of course 1 pixel for the entire chart would not be very useful, BUT should not have errors
*/
}

</style>
 <div id="chart1" class='with-3d-shadow with-transitions'>
    <svg> </svg>
  </div>
<script src="/assets/lib/d3.v3.js"></script>
<script src="/assets/nv.d3.js"></script>
<script src="/assets/src/utils.js"></script>
<script src="/assets/src/tooltip.js"></script>
<script src="/assets/src/models/legend.js"></script>
<script src="/assets/src/models/axis.js"></script>
<script src="/assets/src/models/scatter.js"></script>
<script src="/assets/src/models/line.js"></script>
<script src="/assets/src/models/historicalBar.js"></script>
<script src="/assets/src/models/linePlusBarChart.js"></script>


<script>


var testdata = [
  {
    "key" : "Quantity" ,
    "bar": true,
    "values" : 
    [ 
    <% @parsed_response.each do |r| %>

     [<%= "#{r["date_ms"]}" %>, <%= "#{r["amount"]}" %>],
     <% end %>

    ]
  },
  {
    "key" : "Price" ,
    "values" : [ 
    <% @parsed_response.each do |r| %>
 
     [<%= "#{r["date_ms"]}" %>, <%= "#{r["price"]}" %> * <%= "#{r["amount"]}" %>],
     <% end %>
   ]
  }
].map(function(series) {
  series.values = series.values.map(function(d) { return {x: d[0], y: d[1] } });
  return series;
});


var chart;
nv.addGraph(function() {
    chart = nv.models.linePlusBarChart()
        .margin({top: 30, right: 60, bottom: 50, left: 70})
        .x(function(d,i) { return i })
        .color(d3.scale.category10().range());

    chart.xAxis.tickFormat(function(d) {
      var dx = testdata[0].values[d] && testdata[0].values[d].x || 0;
      return dx ? d3.time.format('%I:%M:%p')(new Date(dx)) : '';
      })
      .showMaxMin(false);

    chart.y1Axis
        .tickFormat(d3.format(',f'));

    chart.y2Axis
        .tickFormat(function(d) { return '$' + d3.format(',.2f')(d) });

    chart.bars.forceY([0]).padData(false);
    //chart.lines.forceY([0]);

    d3.select('#chart1 svg')
        .datum(testdata)
      .transition().duration(500).call(chart);

    nv.utils.windowResize(chart.update);

    chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });

    return chart;
});

</script>
</div>
<%= javascript_tag do %>
  priceUSD = "<%= @parsed_response_chart["market_price_usd"] %>"
<% end %>
<!-- REQUIRE THE D3 LIBRARY Visual Sedimentation -->
<script type="text/javascript" src="/assets/_VisualSedimentation.js"></script> 

<!-- REQUIRE APP.JS FOR THE WEBSOCKET -->
<script type="text/javascript" src="/assets/stats.js"></script> 


 <div class="col-md-3">
    <div class="core-header-panel"><!-- Polymer core element -->
      
       <div class="logo-style"><!-- Logo -->
        <%= link_to image_tag("Federallogo.png"), root_path, method: :get %>
      </div>   

      <div class="center">
      developed by <a class="a2" href="https://www.linkedin.com/profile/view?id=132408717">thirdChance57</a> and <a class="a2" href="https://www.linkedin.com/pub/gregory-akerman/29/663/b78/">Gregory Akerman</a></div>  
      <br>
      <div class="center">
        <!-- <div class="rails-link">
          <strong>
            <%#= link_to "Charts", exchange_path %>
          </strong>
        </div> -->
        <div class="rails-link">
          <strong>
            <%= link_to "Bubble Chart", bubble_path %>
          </strong>
        </div>
      </div><!-- end of center -->
      <br>

      <div class="center">
        <%= form_tag(stats_path, method: "get") do %>
          <%= text_field_tag :addressSearch,nil, placeholder: "Search Bitcoin Address", :class =>"btn-sm" %>
          <%= submit_tag "Search", :class => "btn btn-default btn-sm" %>
        <% end %>
      </div>

      <div class="center">
        
          <h4>Market Price USD: $<%= @parsed_response_chart["market_price_usd"] %></h4><!-- current market price -->
      
      <div>

      <div id="grandtotal" class="center">
          Running Total: <!-- Keeps a running tab of USD grand toatakamount -->
      </div>

      <ul class="nav nav-tabs" style="margin-bottom: 15px;">
        <li class="active">
          <a href="#bitcoins" data-toggle="tab">
            BTC Amount
          </a>
        </li>
        <li>
          <a href="#dollars" data-toggle="tab" >
            Dollar Value
          </a>
        </li>
      </ul>

      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="bitcoins">
          <div id="output" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

        <div class="tab-pane fade" id="dollars">
          <div id="dollar" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

      </div><!-- end of myTabContent -->
  
    </div><!-- end core-header-panel -->

  </div><!-- end col-md-3 -->

</div><!-- end row -->
    <div class="donate a2">
  Donate Please<br>
  <%= link_to"19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", "https://blockchain.info/address/19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", :class => "a2" %>
</div>

</div>

app/views/stats/index.html.erb
<!-- REQUIRE THE D3 LIBRARY Visual Sedimentation -->
<script type="text/javascript" src="/assets/_VisualSedimentation.js"></script> 

<!-- REQUIRE APP.JS FOR THE WEBSOCKET -->
<script type="text/javascript" src="/assets/stats.js"></script> 
<%= javascript_tag do %>
  priceUSD = "<%= @parsed_response["market_price_usd"] %>"
<% end %>
<div class="row" style="font-family: 'Roboto', sans-serif;">
  <div class="col-md-9" style="background-color: white;">
    <!-- Only show if show_data exists and is not blank -->
    <% if @show_data && @show_data != "" %> 
      <% address = @rbody["address"] %>
      <!-- the PriceTotal is the satoshi multiplied by the market price, divided by 100000000 -->
      <% thePriceTotal = @rbody["total_received"] * @parsed_response["market_price_usd"] / 100000000 %>
      <!-- When the page loads, IOlabel is UNKNOWN -->
      <% @IOlabel = "UNKNOWN" %>
    <% end %>
   
    <% if @show_data && @show_data != "" %> 
    <h1>Block Chain Stats for- <strong><%=@rbody["address"] %></strong></h1><br />

    <% end %>
   
    <div class="row"> <!-- Start of first row -->
      <div class="col-md-6">  <!-- Start of col-md-6 -->
        <!-- Only show the results of the api call if show_data exists and is not empty -->

        <% if @show_data && @show_data != "" %> 

          <!-- This table displays the summary information -->
          <table class="table table-striped">
            <tr>
              <td colspan="2"><strong>Summary</strong></td>
            </tr>
            <tr>
              <td>Hash 160</td>
              <td><%=@rbody["hash160"] %></td>
            </tr>
            <tr>
              <td>Address</td>
              <td><%=@rbody["address"] %></td>
            </tr>
          </table>
        <% end %>

      </div>
      <div class="col-md-6">

        <!-- Only show the results of the api call if show_data exists and is not empty -->
        <% if @show_data && @show_data != "" %> 
          <table class="table table-striped">
            <tr>
              <td colspan="2"><strong>Transactions</strong></td>

            </tr>
            <tr>
              <td>Number of Transactions</td>
              <td><%=@rbody["n_tx"] %></td>
            </tr>
            <tr>
              <td>Total Received</td>
              <td><%=number_to_currency(thePriceTotal) %></td>
            </tr>
            <tr>
              <td>Final Balance</td>
              <td><%=@rbody["final_balance"] %></td>
            </tr>
          </table>
        <% end %>
      </div><!-- Let's end col-md-6 -->
    </div> <!-- Let's end row here -->

    <!-- We are starting a new row here -->
    <div class="row" style="font-family: 'Roboto', sans-serif;">
      <div class="col-md-12">
        <table class="table table-striped">
          <tr>
            <td colspan="3"><strong>Transactions</strong> <%= @customError %></td>
          </tr>
          <% if @show_data && @show_data != "" %> 
          <% @trans.each do |one_trans| %>
          <tr>
            <td colspan="2"> TRANSACTION Hash: <%=one_trans["hash"] %>
            </td>
           
          </tr>
          <tr>
            <td width="50%">
              <strong>-- Transaction Senders --</strong><br />
              <% @IOlabel = "" %>
              <% one_trans["inputs"].each do |one_input| %>
              
              <% if one_input["prev_out"]["addr"] == @rbody["address"] %>
               <div class="red"> <strong> <% @IOlabel = "SENDER" %>
              
              <% end %>
                <%= one_input["prev_out"]["addr"] %>- <%= number_to_currency(one_input["prev_out"]["value"] * @parsed_response["market_price_usd"] / 100000000) %><br />
              <% if one_input["prev_out"]["addr"] == @rbody["address"] %>
                </div></strong> 
              <% end %>

              <% end %>
              <br />
              <%=  @IOlabel %>
            </td>
            <td width="50%">
         <strong>--Transaction Receivers--</strong><br />
         <% @IOlabel = "" %>
         <% one_trans["out"].each do |one_out| %>
          <% if one_out["addr"] == @rbody["address"] %>
            <div class="green"> <strong> <% @IOlabel = "RECEIVER" %>
          
          <% end %>
          <%= one_out["addr"] %> - <%= number_to_currency(one_out["value"] * @parsed_response["market_price_usd"] / 100000000) %><br />
          <% if one_out["addr"] == @rbody["address"] %>
          </strong> </div>
          <% end %>
         <% end %>
         <br />
         <%=  @IOlabel %>
       </td>
     </tr>
     <% end %>
     <% end %>




   </table>
 </div>

</div>


  </div>
   <div class="col-md-3">
    <div class="core-header-panel"><!-- Polymer core element -->
        <div class="logo-style"><!-- Logo -->
        <%= link_to image_tag("Federallogo.png"), root_path, method: :get %>
      </div>   

      <div class="center">
      developed by <a class="a2" href="https://www.linkedin.com/profile/view?id=132408717">thirdChance57</a> and <a class="a2" href="https://www.linkedin.com/pub/gregory-akerman/29/663/b78/">Gregory Akerman</a></div>  
      <br>
      <div class="center">
        <!-- <div class="rails-link">
          <strong>
            <%#= link_to "Charts", exchange_path %>
          </strong>
        </div> -->
        <div class="rails-link">
          <strong>
            <%= link_to "Bubble Chart", bubble_path %>
          </strong>
        </div>
      </div><!-- end of center -->
      <br>

      <div class="center">
        <%= form_tag(stats_path, method: "get") do %>
          <%= text_field_tag :addressSearch,nil, placeholder: "Search Bitcoin Address", :class =>"btn-sm" %>
          <%= submit_tag "Search", :class => "btn btn-default btn-sm" %>
        <% end %>
      </div>


      <div class="center">
        
          <h4>Market Price USD: $<%= @parsed_response["market_price_usd"] %></h4><!-- current market price -->
      
      <div>

      <div id="grandtotal" class="center">
          Running Total: <!-- Keeps a running tab of USD grand toatakamount -->
      </div>

      <ul class="nav nav-tabs" style="margin-bottom: 15px;">
        <li class="active">
          <a href="#bitcoins" data-toggle="tab">
            BTC Amount
          </a>
        </li>
        <li>
          <a href="#dollars" data-toggle="tab" >
            Dollar Value
          </a>
        </li>
      </ul>

      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="bitcoins">
          <div id="output" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

        <div class="tab-pane fade" id="dollars">
          <div id="dollar" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

      </div><!-- end of myTabContent -->
  
    </div><!-- end core-header-panel -->
  </div><!-- end col-md-3 -->

</div><!-- end row -->
<div class="donate a2">
  Donate Please<br>
  <%= link_to"19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", "https://blockchain.info/address/19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", :class => "a2" %>
</div>

</div>

app/views/users/edit.html.erb
    <h1> Edit this User! </h1>

    <%= form_for @user do |f| %>
        Username: <%= f.text_field :username %>
        Email: <%= f.text_field :email %>

        <%= f.submit "Edit User!" %>

    <% end %>

    <%= link_to "Back to the list!", users_path %>

app/views/users/show.html.erb
     <h2><%= @user.username %>'s Questions</h2>
            E-Mail: <%= @user.email %><br />
              
            <%= link_to "Edit User", edit_user_path %>

app/views/welcome/bubble.html.erb
<!-- REQUIRE THE D3 LIBRARY Visual Sedimentation -->
<script type="text/javascript" src="/assets/_VisualSedimentation.js"></script> 
<script type="text/javascript" src="/assets/_vs.chart.heapchart.js"></script>


<!-- REQUIRE APP.JS FOR THE WEBSOCKET -->
<script type="text/javascript" src="/assets/app_bubble.js"></script>

<!-- creates a var=priceUSD for JS -->
<%= javascript_tag do %>
  priceUSD = "<%= @parsed_response["market_price_usd"] %>"
<% end %>

<div class="row">

  <div class="col-md-9" style="background-color: white;">

    <div class="btn-center">
      <button class="btn btn-default" onclick="toggleBitcoin()" >Bitcoin Loading</button> 
      <button class="btn btn-default" onclick="toggleDogecoin()">Dogecoin Loading</button>
      <div class="token-click" id="btc-callback">
        <div></div><!-- required for replaceChild -->
      </div>
      <div class="token-click" id="doge-callback2">
        <div></div><!-- required for replaceChild -->
      </div>
    </div>

    <div class="content">
      <!--- #myDemo now has a css rule -->
      <div id="heatchart">
        <script type="text/javascript" src="/assets/bubble.js"></script>
      </div>
    </div> 

  </div><!-- end col-md-9 -->

  <div class="col-md-3">
    <div class="core-header-panel"><!-- Polymer core element -->
     <div class="logo-style"><!-- Logo -->
        <%= link_to image_tag("Federallogo.png"), root_path, method: :get %>
      </div>   

      <div class="center">
      developed by <a class="a2" href="https://www.linkedin.com/profile/view?id=132408717">thirdChance57</a> and <a class="a2" href="https://www.linkedin.com/pub/gregory-akerman/29/663/b78/">Gregory Akerman</a></div>  
      <div class="donate a2">
        Donate: &nbsp;<%= link_to"19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", "https://blockchain.info/address/19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", :class => "a2" %>
      </div>
      <hr>
      <div class="center">
        <!-- <div class="rails-link">
          <strong>
            <%#= link_to "Charts", exchange_path %>
          </strong>
        </div> -->
        <div class="rails-link">
          <strong>
            <%= link_to "Gravity Chart", root_path %> &nbsp; <a href="#" class="disabled">Bubble Chart</a>
          </strong>
        </div>
      </div><!-- end of center -->
      <br>

 
      <div class="center">
        <%= form_tag(stats_path, method: "get") do %>
          <%= text_field_tag :addressSearch,nil, placeholder: "Search Bitcoin Address", :class =>"btn-sm" %>
          <%= submit_tag "Search", :class => "btn btn-default btn-sm" %>
        <% end %>
      </div>

      <div class="center">
        <h4>BTC Market Price USD: $<%= @parsed_response["market_price_usd"] %></h4><!-- current market price -->
        <div id="grandtotal">
            Running Total: <!-- Keeps a running tab of USD grand toatakamount -->
        </div>
      </div>
      <ul class="nav nav-tabs" style="margin-bottom: 15px;">
        <li class="active">
          <a href="#bitcoins" data-toggle="tab">
            BTC Amount
          </a>
        </li>
        <li>
          <a href="#dollars" data-toggle="tab" >
            Dollar Value
          </a>
        </li>
      </ul>

      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="bitcoins">
          <div id="output" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

        <div class="tab-pane fade" id="dollars">
          <div id="dollar" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div><!-- end of tab-pane -->
      </div><!-- end of myTabContent -->
    </div><!-- end core-header-panel -->
    <div class="donate a2">
      Donate Please<br>
      <%= link_to"19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", "https://blockchain.info/address/19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", :class => "a2" %>
    </div>
  </div><!-- end col-md-3 -->
</div><!-- end row -->

app/views/welcome/index.html.erb
<!-- REQUIRE THE D3 LIBRARY Visual Sedimentation -->
<script type="text/javascript" src="/assets/_VisualSedimentation.js"></script> 
<!-- REQUIRE APP.JS FOR THE WEBSOCKET -->
<script type="text/javascript" src="/assets/app.js"></script> 
<!-- creates a var=priceUSD for JS -->
<%= javascript_tag do %>
  priceUSD = "<%= @parsed_response["market_price_usd"] %>"
<% end %>

<div class="row">
  <!-- Style tag removes the grey padding to the right. -->
  <div class="col-md-9 bg-white" style="padding-right: 0px;">
    <div class="btn-center"> <!-- start of buttons to turn off and on BTC and DOGE -->
      <button class="btn btn-default" onclick="toggleBitcoin()" >Bitcoin Loading</button> 
      <button class="btn btn-default" onclick="toggleDogecoin()">Dogecoin Loading</button>
      <div class="token-click" id="btc-callback">
        <div></div><!-- required for replaceChild -->
      </div>
      <div class="token-click" id="doge-callback2">
        <div></div><!-- required for replaceChild -->
      </div>
    </div>
    <div class="content">
      <!--- #myDemo now has a css rule -->
      <div id="myDemo">
        <script type="text/javascript" src="/assets/moneyFalling.js"></script>
      </div>
    </div> 
  </div><!-- end col-md-9 -->

  <div class="col-md-3">
    <div class="core-header-panel"><!-- Polymer core element -->
      <div class="logo-style"><!-- Logo -->
        <%= link_to image_tag("Federallogo.png"), root_path, method: :get %>
      </div>   

      <div class="center">
      by: <a class="a2" href="https://www.linkedin.com/profile/view?id=132408717">thirdChance57</a> and <a class="a2" href="https://www.linkedin.com/pub/gregory-akerman/29/663/b78/">Gregory Akerman</a></div>  
      <div class="donate a2">
        Donate if you appreciate this app<br>
        <%= link_to"19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", "https://blockchain.info/address/19htWM6ceqkjguY7TezEeybSE2LzvSfqYk", :class => "a2" %>
      </div>
      <hr class="m-0">
      <div class="center">
        <!-- <div class="rails-link">
          <strong>
            <%#= link_to "Charts", exchange_path %>
          </strong>
        </div> -->
        <div class="rails-link">
          <strong>
            <a href="#" class="disabled">Gravity Chart</a> &nbsp; <%= link_to "Bubble Chart", bubble_path %>
          </strong>
        </div>
      </div><!-- end of center -->
      <br>

      <div class="center">
        <%= form_tag(stats_path, method: "get") do %>
          <%= text_field_tag :addressSearch,nil, placeholder: "Search Bitcoin Address", :class =>"btn-sm" %>
          <%= submit_tag "Search", :class => "btn btn-default btn-sm" %>
        <% end %>
      </div>

      <div class="center">
        <h4>BTC Market Price USD: $<%= @parsed_response["market_price_usd"] %></h4><!-- current market price -->
        <div id="grandtotal">
            Running Total: <!-- Keeps a running tab of USD grand toatakamount -->
        </div>
      </div>
      <ul class="nav nav-tabs" style="margin-bottom: 15px;">
        <li class="active">
          <a href="#bitcoins" data-toggle="tab">
            BTC Amount
          </a>
        </li>
        <li>
          <a href="#dollars" data-toggle="tab" >
            Dollar Value
          </a>
        </li>
      </ul>

      <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="bitcoins">
          <div id="output" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div>

        <div class="tab-pane fade" id="dollars">
          <div id="dollar" class="btclist">
            <div></div><!-- required for .insertBefore -->
          </div>
        </div><!-- end of tab-pane -->
      </div><!-- end of myTabContent -->
    </div><!-- end core-header-panel -->
  </div><!-- end col-md-3 -->
</div><!-- end row -->